const LessonsActionTypes = {
  REQUEST_ALL_LESSONS : 'REQUEST_ALL_LESSONS',
  SUCCESS_ALL_LESSONS : 'SUCCESS_ALL_LESSONS',
  FAILUER_ALL_LESSONS : 'FAILUER_ALL_LESSONS',
  REQUEST_ALL_TIMETABLES : 'REQUEST_ALL_TIMETABLES',
  SUCCESS_ALL_TIMETABLES : 'SUCCESS_ALL_TIMETABLES',
  FAILUER_ALL_TIMETABLES : 'FAILUER_ALL_TIMETABLES',
  REQUEST_GET_TIMETABLES : 'REQUEST_GET_TIMETABLES',
  SUCCESS_GET_TIMETABLES : 'SUCCESS_GET_TIMETABLES',
  FAILUER_GET_TIMETABLES : 'FAILUER_GET_TIMETABLES',
  REQUEST_POST_TIMETABLES : 'REQUEST_POST_TIMETABLES',
  SUCCESS_POST_TIMETABLES : 'SUCCESS_POST_TIMETABLES',
  FAILUER_POST_TIMETABLES : 'FAILUER_POST_TIMETABLES',
  REQUEST_PUT_TIMETABLES : 'REQUEST_PUT_TIMETABLES',
  SUCCESS_PUT_TIMETABLES : 'SUCCESS_PUT_TIMETABLES',
  FAILUER_PUT_TIMETABLES : 'FAILUER_PUT_TIMETABLES',
  REQUEST_DELETE_TIMETABLES : 'REQUEST_DELETE_TIMETABLES',
  SUCCESS_DELETE_TIMETABLES : 'SUCCESS_DELETE_TIMETABLES',
  FAILUER_DELETE_TIMETABLES : 'FAILUER_DELETE_TIMETABLES'
}

export default LessonsActionTypes
