const LessonsActionTypes = {
  REQUEST_ALL_LESSONS : 'REQUEST_ALL_LESSONS',
  SUCCESS_ALL_LESSONS : 'SUCCESS_ALL_LESSONS',
  FAILUER_ALL_LESSONS : 'FAILUER_ALL_LESSONS'
}

export default LessonsActionTypes
