const UsersActionTypes = {
  REQUEST_ALL_USERS : 'REQUEST_ALL_USERS',
  SUCCESS_ALL_USERS : 'SUCCESS_ALL_USERS',
  FAILUER_ALL_USERS : 'FAILUER_ALL_USERS',
  REQUEST_GET_USERS : 'REQUEST_GET_USERS',
  SUCCESS_GET_USERS : 'SUCCESS_GET_USERS',
  FAILUER_GET_USERS : 'FAILUER_GET_USERS',
  REQUEST_MY_USERS : 'REQUEST_MY_USERS',
  SUCCESS_MY_USERS : 'SUCCESS_MY_USERS',
  FAILUER_MY_USERS : 'FAILUER_MY_USERS',
  REQUEST_PUT_USERS : 'REQUEST_PUT_USERS',
  SUCCESS_PUT_USERS : 'SUCCESS_PUT_USERS',
  FAILUER_PUT_USERS : 'FAILUER_PUT_USERS'
}

export default UsersActionTypes
