const UsersActionTypes = {
  REQUEST_ALL_USERS : 'REQUEST_ALL_USERS',
  SUCCESS_ALL_USERS : 'SUCCESS_ALL_USERS',
  FAILUER_ALL_USERS : 'FAILUER_ALL_USERS',
  REQUEST_GET_USERS : 'REQUEST_GET_USERS',
  SUCCESS_GET_USERS : 'SUCCESS_GET_USERS',
  FAILUER_GET_USERS : 'FAILUER_GET_USERS'
}

export default UsersActionTypes
