const AuthActionTypes = {
  REQUEST_LOGIN : 'REQUEST_LOGIN',
  SUCCESS_LOGIN : 'SUCCESS_LOGIN',
  FAILUER_LOGIN : 'FAILUER_LOGIN',
  REQUEST_LOGOUT : 'REQUEST_LOGOUT',
  SUCCESS_LOGOUT : 'SUCCESS_LOGOUT',
  SUCCESS_AUTH : 'SUCCESS_AUTH'
}

export default AuthActionTypes
